### ISSUE TITLE
Remove Users from Group returns 404 error

### ISSUE THREAD

**Issue by Firebirdjim** [Mindflash/mf-api-example#1]
While Remove User from Group works fine, Remove Users from Group seems to return an error even when used via the API sandbox:

![remove-users-from-group-error](https://cloud.githubusercontent.com/assets/907892/4996586/644e69b2-6996-11e4-8079-39180d6b2391.jpg)

I also tried using the function by sending a DELETE request to it via CURL, and got the same error message of "Cannot DELETE"

**Comment by larsenjh** [comment]
The API endpoint for this function was incorrect in the docs. Updated docs to reflect correct usage.
